<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcp8swt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcp8swt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWcp8swt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWcp8swt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWcp8swt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wcp8swt',
    'container.build_id' => '7bb4fc51',
    'container.build_time' => 1582297349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcp8swt');
